name: False Positive Report
description: Report a false positive detection
title: "[FALSE POSITIVE] "
labels: ["false-positive", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve detection accuracy by reporting false positives!

  - type: textarea
    id: detection
    attributes:
      label: What Was Detected
      description: What secret type was incorrectly flagged?
      placeholder: |
        Secret Type: AWS Access Key
        Pattern matched: AKIA...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Code Context
      description: Provide the code that was flagged (redact if sensitive)
      placeholder: |
        ```javascript
        const example = "AKIAIOSFODNN7EXAMPLE";  // AWS docs example
        ```
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: reason
    attributes:
      label: Why Is This a False Positive?
      description: Select the most applicable reason
      options:
        - Example/placeholder value
        - Test data
        - Documentation
        - Comment explaining real secret
        - Other (explain below)
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: How should leaktor handle this case?
      placeholder: Maybe check if the value matches AWS's official example...
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Leaktor Version
      description: Run `leaktor --version`
      placeholder: v0.1.0
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false
